pipeline:
  name: petclinic-ci-new
  identifier: petcliniccinew
  projectIdentifier: SE_Candidate_Lab
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_petclinic
        build: <+input>
  stages:
    - stage:
        name: Build and Test
        identifier: build_and_test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: true
            paths: []
          buildIntelligence:
            enabled: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8s_docker_desktop
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build
                  identifier: Build
                  spec:
                    connectorRef: dockerhub_petclinic
                    image: maven:3.9.6-eclipse-temurin-8
                    shell: Sh
                    command: |
                      echo "MAVEN_CONFIG pre-unset: ${MAVEN_CONFIG:-unset}"
                      unset MAVEN_CONFIG
                      echo "MAVEN_CONFIG post-unset: ${MAVEN_CONFIG:-unset}"

                      chmod +x mvnw
                      ./mvnw -v
                      ./mvnw -B -Dmaven.repo.local=/harness/maven-repo -DskipTests clean package
              - step:
                  type: Run
                  name: Check Dependencies
                  identifier: Check_Dependencies
                  spec:
                    connectorRef: dockerhub_petclinic
                    image: maven:3.9.6-eclipse-temurin-8
                    shell: Sh
                    command: |
                      echo "MAVEN_CONFIG pre-unset: ${MAVEN_CONFIG:-unset}"
                      unset MAVEN_CONFIG
                      echo "MAVEN_CONFIG post-unset: ${MAVEN_CONFIG:-unset}"

                      ./mvnw -B -Dmaven.repo.local=/harness/maven-repo -DskipTests org.owasp:dependency-check-maven:check
              - step:
                  type: Run
                  name: Unit Tests
                  identifier: unit_tests
                  spec:
                    connectorRef: dockerhub_petclinic
                    image: maven:3.9.6-eclipse-temurin-8
                    shell: Sh
                    command: |
                      echo "MAVEN_CONFIG pre-unset: ${MAVEN_CONFIG:-unset}"
                      unset MAVEN_CONFIG
                      echo "MAVEN_CONFIG post-unset: ${MAVEN_CONFIG:-unset}"

                      ./mvnw -B -Dmaven.repo.local=/harness/maven-repo test
    - stage:
        name: Build Image and Push
        identifier: Buildpack_Image
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: true
            paths: []
          buildIntelligence:
            enabled: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8s_docker_desktop
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push
                  identifier: build_push_pack
                  spec:
                    connectorRef: dockerhub_petclinic
                    repo: areger55/harness-se-lab-dockerhub-repo
                    tags:
                      - <+codebase.commitSha>
                      - latest
                    caching: false
                    buildTool: Buildpacks
                    buildpacks:
                      builder: paketobuildpacks/builder:base
                      runImage: paketobuildpacks/run:base-cnb
                      env:
                        BP_JVM_VERSION: "8"
