pipeline:
  name: petclinic-optimized
  identifier: petclinic_optimized
  projectIdentifier: SE_Candidate_Lab
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_petclinic
        repoName: adamreger/spring-petclinic-k8s
        build: <+input>
  variables:
    - name: DEPLOY_ENV
      type: String
      value: <+input>.default(dev).selectOneFrom(dev,stg,prd)
    - name: SKIP_DEPCHECK
      type: String
      value: <+input>.default(false).selectOneFrom(true,false)
    - name: SKIP_BUILD_TEST
      type: String
      value: <+input>.default(false).selectOneFrom(true,false)
    - name: CANARY_POD_COUNT
      type: Number
      value: <+input>.default(1)
  stages:
    - stage:
        name: Build and Package
        identifier: build_package
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8s_docker_desktop
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build All Modules
                  identifier: mvn_build_all
                  strategy:
                    matrix:
                      module:
                        - spring-petclinic-api-gateway
                        - spring-petclinic-customers-service
                        - spring-petclinic-vets-service
                        - spring-petclinic-visits-service
                  spec:
                    connectorRef: dockerhub_petclinic
                    image: maven:3.9.6-eclipse-temurin-8
                    shell: Sh
                    command: |-
                      unset MAVEN_CONFIG
                      chmod +x mvnw
                      export MAVEN_OPTS="-Xmx2g"
                      mkdir -p /harness/.m2/repository

                      echo "Building module: $MODULE"
                      ./mvnw -B -pl "$MODULE" -am clean package -DskipTests \
                        -Dmaven.repo.local=/harness/.m2/repository

                      # Verify JAR was created
                      echo "=== Built JAR for $MODULE ==="
                      find ${MODULE}/target -name "*.jar" -type f | head -5
                    envVariables:
                      MODULE: <+matrix.module>
                    resources:
                      limits:
                        memory: 2G
              - step:
                  type: Run
                  name: Prepare Artifacts
                  identifier: prepare_artifacts
                  spec:
                    connectorRef: dockerhub_petclinic
                    image: alpine:3.18
                    shell: Sh
                    command: |
                      echo "=== Organizing artifacts for caching ==="

                      # Create artifacts directory at a known location
                      mkdir -p /harness/artifacts

                      # Copy JARs with standardized naming
                      echo "Collecting JARs..."

                      cp spring-petclinic-api-gateway/target/*.jar /harness/artifacts/api-gateway.jar 2>/dev/null || echo "Warning: Gateway JAR not found"
                      cp spring-petclinic-customers-service/target/*.jar /harness/artifacts/customers-service.jar 2>/dev/null || echo "Warning: Customers JAR not found"
                      cp spring-petclinic-vets-service/target/*.jar /harness/artifacts/vets-service.jar 2>/dev/null || echo "Warning: Vets JAR not found"
                      cp spring-petclinic-visits-service/target/*.jar /harness/artifacts/visits-service.jar 2>/dev/null || echo "Warning: Visits JAR not found"

                      # Display collected artifacts
                      echo ""
                      echo "=== Artifacts ready for caching ==="
                      ls -lh /harness/artifacts/
                      echo ""
                      echo "Total size: $(du -sh /harness/artifacts/ | cut -f1)"
              - step:
                  type: SaveCacheS3
                  name: Save Build Artifacts to S3
                  identifier: save_build_artifacts_to_s3
                  spec:
                    connectorRef: harnessbuilddependencycache
                    region: us-west-1
                    bucket: harness-build-dependency-cache
                    key: artifacts/<+codebase.repoName>/<+codebase.branch>/<+codebase.commitSha>
                    sourcePaths:
                      - /harness/artifacts
                    archiveFormat: Tar
                    override: true
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
        description: Build all JAR artifacts once and cache them
    - stage:
        name: Security and Quality Checks
        identifier: security_quality
        description: Run security scans and tests on built artifacts
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            useFromStage: build_package
          execution:
            steps:
              - step:
                  type: RestoreCacheS3
                  name: Restore Artifacts from S3
                  identifier: restore_artifacts_from_s3
                  spec:
                    connectorRef: harnessbuilddependencycache
                    region: us-west-1
                    bucket: harness-build-dependency-cache
                    key: artifacts/<+codebase.repoName>/<+codebase.branch>/<+codebase.commitSha>
                    archiveFormat: Tar
              - step:
                  type: Run
                  name: Verify Cached Artifacts
                  identifier: verify_artifacts
                  spec:
                    connectorRef: dockerhub_petclinic
                    image: alpine:3.18
                    shell: Sh
                    command: |-
                      echo "=== Verifying cached artifacts ==="
                      ls -lh /harness/artifacts/

                      # Verify each required JAR exists
                      for jar in api-gateway.jar customers-service.jar vets-service.jar visits-service.jar; do
                        if [ -f "/harness/artifacts/${jar}" ]; then
                          echo "✓ ${jar} found ($(du -h /harness/artifacts/${jar} | cut -f1))"
                        else
                          echo "✗ ${jar} NOT FOUND!"
                          exit 1
                        fi
                      done

                      echo ""
                      echo "✓ Successfully restored all artifacts from S3 build cache"
              - step:
                  type: Owasp
                  name: OWASP Dependency Check
                  identifier: OWASP_Dependency_Check
                  when:
                    stageStatus: Success
                    condition: |
                      <+pipeline.variables.SKIP_DEPCHECK> == "false" || <+pipeline.variables.DEPLOY_ENV> == "stg" || <+pipeline.variables.DEPLOY_ENV> == "prd"
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: debug
                      fail_on_severity: none
                      args:
                        cli: "--disableOssIndex"
                    privileged: true
              - step:
                  type: RunTests
                  name: Unit Tests
                  identifier: unit_tests
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.SKIP_BUILD_TEST> == "false" || <+pipeline.variables.DEPLOY_ENV> == "stg" ||  <+pipeline.variables.DEPLOY_ENV> == "prd"
                  spec:
                    connectorRef: dockerhub_petclinic
                    image: maven:3.9.6-eclipse-temurin-8
                    language: Java
                    buildTool: Maven
                    args: test
                    runOnlySelectedTests: false
                    preCommand: |
                      echo "Running tests with cached dependencies"
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/target/surefire-reports/*.xml"
                    envVariables:
                      MAVEN_OPTS: "-Xms512m"
                      NVD_API_KEY: <+secrets.getValue("NVD_API_KEY")>
                    resources:
                      limits:
                        memory: 4Gi
                        cpu: "2"
                    enableTestSplitting: false
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: Ignore
          caching:
            enabled: true
          buildIntelligence:
            enabled: false
    - stage:
        name: Build and Push Container Images
        identifier: build_push_images
        description: Build Docker images from cached JAR artifacts
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8s_docker_desktop
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: RestoreCacheS3
                  name: Restore Artifacts from S3
                  identifier: Restore_Artifacts_from_S3
                  spec:
                    connectorRef: harnessbuilddependencycache
                    region: us-west-1
                    bucket: harness-build-dependency-cache
                    key: artifacts/<+codebase.repoName>/<+codebase.branch>/<+codebase.commitSha>
                    archiveFormat: Tar
              - step:
                  type: Run
                  name: Verify Artifacts for Docker Build
                  identifier: verify_artifacts_docker
                  spec:
                    connectorRef: dockerhub_petclinic
                    image: alpine:3.18
                    shell: Sh
                    command: |-
                      echo "=== Verifying artifacts for Docker builds ==="
                      ls -lh /harness/artifacts/

                      # Verify each required JAR exists
                      for jar in api-gateway.jar customers-service.jar vets-service.jar visits-service.jar; do
                        if [ -f "/harness/artifacts/${jar}" ]; then
                          echo "✓ ${jar} found ($(du -h /harness/artifacts/${jar} | cut -f1))"
                        else
                          echo "✗ ${jar} NOT FOUND!"
                          exit 1
                        fi
                      done

                      echo ""
                      echo "✓ Successfully restored all artifacts from S3 build cache"
              - stepGroup:
                  name: Build All Images
                  identifier: Build_All_Images
                  steps:
                    - step:
                        type: BuildAndPushDockerRegistry
                        name: API Gateway Image
                        identifier: build_push_gateway
                        spec:
                          connectorRef: dockerhub_push
                          repo: areger55/harness-se-lab-dockerhub-repo
                          tags:
                            - gateway-<+codebase.commitSha>
                            - gateway-latest
                          context: /harness
                          dockerfile: /harness/Optimized.Dockerfile
                          caching: true
                          buildArgs:
                            JAR_FILE: artifacts/api-gateway.jar
                          resources:
                            limits:
                              memory: 2Gi
                              cpu: "1"
                    - step:
                        type: BuildAndPushDockerRegistry
                        name: Customers Image
                        identifier: build_push_customers
                        spec:
                          connectorRef: dockerhub_push
                          repo: areger55/harness-se-lab-dockerhub-repo
                          tags:
                            - customers-<+codebase.commitSha>
                            - customers-latest
                          context: /harness
                          dockerfile: /harness/Optimized.Dockerfile
                          caching: true
                          buildArgs:
                            JAR_FILE: artifacts/customers-service.jar
                          resources:
                            limits:
                              memory: 2Gi
                              cpu: "1"
                    - step:
                        type: BuildAndPushDockerRegistry
                        name: Vets Image
                        identifier: build_push_vets
                        spec:
                          connectorRef: dockerhub_push
                          repo: areger55/harness-se-lab-dockerhub-repo
                          tags:
                            - vets-<+codebase.commitSha>
                            - vets-latest
                          context: /harness
                          dockerfile: /harness/Optimized.Dockerfile
                          caching: true
                          buildArgs:
                            JAR_FILE: artifacts/vets-service.jar
                          resources:
                            limits:
                              memory: 2Gi
                              cpu: "1"
                    - step:
                        type: BuildAndPushDockerRegistry
                        name: Visits Image
                        identifier: build_push_visits
                        spec:
                          connectorRef: dockerhub_push
                          repo: areger55/harness-se-lab-dockerhub-repo
                          tags:
                            - visits-<+codebase.commitSha>
                            - visits-latest
                          context: /harness
                          dockerfile: /harness/Optimized.Dockerfile
                          caching: true
                          buildArgs:
                            JAR_FILE: artifacts/visits-service.jar
                          resources:
                            limits:
                              memory: 2Gi
                              cpu: "1"
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: true
    - parallel:
        - stage:
            name: Deploy Customers
            identifier: deploy_customers
            tags: {}
            template:
              templateRef: K8s_Canary_Deploy_v2
              versionLabel: v1
              templateInputs:
                type: Deployment
                variables:
                  - name: envRef
                    type: String
                    value: <+pipeline.variables.DEPLOY_ENV>
                  - name: serviceName
                    type: String
                    value: customersservice
                  - name: appName
                    type: String
                    value: customers
                  - name: canaryCount
                    type: Number
                    value: <+pipeline.variables.CANARY_POD_COUNT>
        - stage:
            name: Deploy Vets
            identifier: deploy_vets
            tags: {}
            template:
              templateRef: K8s_Canary_Deploy_v2
              versionLabel: v1
              templateInputs:
                type: Deployment
                variables:
                  - name: envRef
                    type: String
                    value: <+pipeline.variables.DEPLOY_ENV>
                  - name: serviceName
                    type: String
                    value: vetsservice
                  - name: appName
                    type: String
                    value: vets
                  - name: canaryCount
                    type: Number
                    value: <+pipeline.variables.CANARY_POD_COUNT>
        - stage:
            name: Deploy Visits
            identifier: deploy_visits
            tags: {}
            template:
              templateRef: K8s_Canary_Deploy_v2
              versionLabel: v1
              templateInputs:
                type: Deployment
                variables:
                  - name: envRef
                    type: String
                    value: <+pipeline.variables.DEPLOY_ENV>
                  - name: serviceName
                    type: String
                    value: visitsservice
                  - name: appName
                    type: String
                    value: visits
                  - name: canaryCount
                    type: Number
                    value: <+pipeline.variables.CANARY_POD_COUNT>
        - stage:
            name: Deploy Gateway
            identifier: deploy_gateway
            tags: {}
            template:
              templateRef: K8s_Canary_Deploy_v2
              versionLabel: v1
              templateInputs:
                type: Deployment
                variables:
                  - name: envRef
                    type: String
                    value: <+pipeline.variables.DEPLOY_ENV>
                  - name: serviceName
                    type: String
                    value: apigatewayservice
                  - name: appName
                    type: String
                    value: gateway
                  - name: canaryCount
                    type: Number
                    value: <+pipeline.variables.CANARY_POD_COUNT>
