pipeline:
  name: petclinic-ci
  identifier: petcliniccinew
  projectIdentifier: SE_Candidate_Lab
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_petclinic
        build: <+input>
  variables:
    - name: RUN_DEPCHECK
      type: String
      value: "false"
  stages:
    - stage:
        name: Build and Test
        identifier: build_and_test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: true
            paths: []
          buildIntelligence:
            enabled: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8s_docker_desktop
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build
                  identifier: Build
                  spec:
                    shell: Sh
                    image: maven:3.9.6-eclipse-temurin-8
                    connectorRef: dockerhub_petclinic
                    envVariables:
                      NVD_API_KEY: <+secrets.getValue("NVD_API_KEY")>
                    resources:
                      limits:
                        memory: 3Gi
                        cpu: "2"
                      requests:
                        memory: 1Gi
                        cpu: "1"
                    command: |
                      unset MAVEN_CONFIG
                      chmod +x mvnw
                      java -version && ./mvnw -v
                      export MAVEN_OPTS="-Xms512m -Xmx1536m -XX:MaxMetaspaceSize=512m"
                      ./mvnw -B -Dmaven.repo.local=/harness/maven-repo -DskipTests clean package
              - step:
                  type: Run
                  name: Check Dependencies
                  identifier: Check_Dependencies
                  spec:
                    connectorRef: dockerhub_petclinic
                    image: maven:3.9.6-eclipse-temurin-8
                    shell: Sh
                    command: |-
                      unset MAVEN_CONFIG
                      export MAVEN_OPTS="-Xms256m -Xmx1024m -XX:MaxMetaspaceSize=384m"
                      ./mvnw -B \
                      -Dmaven.repo.local=/harness/maven-repo \
                      -DnvdApiKey=${NVD_API_KEY} \
                      -DskipTests \
                      org.owasp:dependency-check-maven:check
                    envVariables:
                      NVD_API_KEY: <+secrets.getValue("NVD_API_KEY")>
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.RUN_DEPCHECK> == "true"
              - step:
                  type: RunTests
                  name: Unit Tests
                  identifier: unit_tests
                  spec:
                    language: Java
                    buildTool: Maven
                    args: test
                    image: maven:3.9.6-eclipse-temurin-8
                    connectorRef: dockerhub_petclinic
                    additionalArgs: "-B -DnvdApiKey=${NVD_API_KEY} -Dmaven.repo.local=/harness/maven-repo -DargLine='-Xmx1024m -XX:MaxMetaspaceSize=512m' -DforkCount=1"
                    runOnlySelectedTests: false
                    resources:
                      limits:
                        memory: 3Gi
                        cpu: "2"
                      requests:
                        memory: 1Gi
                        cpu: "1"
                    envVariables:
                      NVD_API_KEY: <+secrets.getValue("NVD_API_KEY")>
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/surefire-reports/*.xml
    - stage:
        name: Build Image and Push
        identifier: Buildpack_Image
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: true
            paths: []
          buildIntelligence:
            enabled: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8s_docker_desktop
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push
                  identifier: build_push_pack
                  spec:
                    connectorRef: dockerhub_petclinic
                    repo: areger55/harness-se-lab-dockerhub-repo
                    tags:
                      - <+codebase.commitSha>
                      - latest
                    caching: false
                    buildTool: Buildpacks
                    buildpacks:
                      builder: paketobuildpacks/builder:base
                      runImage: paketobuildpacks/run:base-cnb
                      env:
                        BP_JVM_VERSION: "8"
                        BP_MAVEN_BUILD_ARGUMENTS: "-DskipTests -Dmaven.repo.local=/workspace/.m2 clean package"
