pipeline:
  name: petclinic-ci-cd
  identifier: petclinic_ci_cd
  projectIdentifier: SE_Candidate_Lab
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_petclinic
        repoName: adamreger/spring-petclinic-k8s
        build: <+input>
  variables:
    - name: SKIP_DEPCHECK
      type: String
      value: <+input>.default(true).selectOneFrom(true,false)
    - name: SKIP_DEPCHECK_NEW
      type: String
      value: <+input>.default(true).selectOneFrom(true,false)
    - name: SKIP_BUILD_TEST
      type: String
      value: <+input>.default(false).selectOneFrom(true,false)
    - name: CANARY_POD_COUNT
      type: String
      value: <+input>.default(1)
  stages:
    - stage:
        name: Maven Build
        identifier: Build_Test
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8s_docker_desktop
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build
                  identifier: mvn_build
                  strategy:
                    matrix:
                      module:
                        - spring-petclinic-api-gateway
                        - spring-petclinic-customers-service
                        - spring-petclinic-vets-service
                        - spring-petclinic-visits-service
                  spec:
                    connectorRef: dockerhub_petclinic
                    image: maven:3.9.6-eclipse-temurin-8
                    shell: Sh
                    command: mvn -B -pl "$MODULE" -am clean package -DskipTests
                    envVariables:
                      NVD_API_KEY: <+secrets.getValue("NVD_API_KEY")>
                      MODULE: <+matrix.module>
          caching:
            enabled: true
            paths: []
          buildIntelligence:
            enabled: true
        description: ""
    - stage:
        name: Run Tests
        identifier: Run_Tests
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            paths: []
          buildIntelligence:
            enabled: true
          infrastructure:
            useFromStage: Build_Test
          execution:
            steps:
              - step:
                  type: Run
                  name: Check Dependencies
                  identifier: Check_Dependencies
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.SKIP_DEPCHECK> == "false"
                  spec:
                    connectorRef: dockerhub_petclinic
                    image: maven:3.9.6-eclipse-temurin-17
                    shell: Sh
                    envVariables:
                      NVD_API_KEY: <+secrets.getValue("NVD_API_KEY")>
                    command: |-
                      unset MAVEN_CONFIG
                      export MAVEN_OPTS="-Xms256m -Xmx1024m -XX:MaxMetaspaceSize=384m"
                      DC_VERSION=12.0.2
                      DC_ARCHIVE="dependency-check-cli-${DC_VERSION}-release.zip"
                      DC_BASE_PATH="${HOME}/.dependency-check"
                      DC_BIN="${DC_BASE_PATH}/${DC_VERSION}"
                      mkdir -p "${DC_BIN}"
                      if [ ! -d "${DC_BIN}/dependency-check" ]; then
                        DC_URL="https://repo1.maven.org/maven2/org/owasp/dependency-check-cli/${DC_VERSION}/${DC_ARCHIVE}"
                        echo "Downloading OWASP Dependency-Check CLI ${DC_VERSION} from ${DC_URL}"
                        APT_UPDATED=false
                        if ! command -v curl >/dev/null 2>&1; then
                          apt-get update && apt-get install -y curl
                          APT_UPDATED=true
                        fi
                        if ! command -v unzip >/dev/null 2>&1; then
                          if [ "${APT_UPDATED}" = "false" ]; then
                            apt-get update
                          fi
                          apt-get install -y unzip
                        fi
                        rm -rf "${DC_BIN:?}/${DC_ARCHIVE}" "${DC_BIN:?}/dependency-check"
                        curl -fsSL "${DC_URL}" -o "${DC_BIN}/${DC_ARCHIVE}"
                        unzip -q "${DC_BIN}/${DC_ARCHIVE}" -d "${DC_BIN}"
                      else
                        echo "Reusing cached Dependency-Check CLI ${DC_VERSION}"
                      fi
                      DC_HOME="${DC_BIN}/dependency-check"
                      DC_DATA_DIR="${DC_BASE_PATH}/data"
                      rm -rf "${DC_DATA_DIR}"
                      mkdir -p "${DC_DATA_DIR}"
                      echo "Updating vulnerability database"
                      "${DC_HOME}/bin/dependency-check.sh" \
                        --data "${DC_DATA_DIR}" \
                        --updateonly \
                        --nvdApiKey "${NVD_API_KEY}" \
                        --nvdApiDelay 4000
                      echo "Running OWASP Dependency-Check CLI ${DC_VERSION}"
                      mkdir -p dependency-check-report
                      "${DC_HOME}/bin/dependency-check.sh" \
                        --project "spring-petclinic" \
                        --scan "spring-petclinic-api-gateway" \
                        --out "dependency-check-report" \
                        --data "${DC_DATA_DIR}" \
                        --format "HTML" \
                        --format "JSON" \
                        --noupdate \
                        --failOnCVSS 11
                      echo "Dependency-Check reports generated under dependency-check-report/"
              - step:
                  type: Run
                  name: OWASP Dependency Check
                  identifier: owasp_dependency_check
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.SKIP_DEPCHECK_NEW> == "false"
                  spec:
                    connectorRef: dockerhub_petclinic
                    image: maven:3.9.6-eclipse-temurin-17
                    shell: Sh
                    envVariables:
                      NVD_API_KEY: <+secrets.getValue("NVD_API_KEY")>
                    command: |
                      # Clean up any previously cached plugin artifacts to avoid version conflicts
                      rm -rf /harness/.m2/repository/org/owasp/dependency-check-maven/

                      # Run OWASP Dependency Check with Java 17 compatible settings
                      mvn -B -Dmaven.repo.local=/harness/.m2/repository \
                        org.owasp:dependency-check-maven:check \
                        -DfailBuildOnCVSS=7 \
                        -Dformat=ALL \
                        -DprettyPrint=true \
                        -DnvdApiKey=${NVD_API_KEY} \
                        -DskipSystemScope=false

                      # Check if vulnerabilities were found
                      if [ -f target/dependency-check-report.html ]; then
                        echo "Dependency check report generated successfully"
                        echo "Report location: target/dependency-check-report.html"
                      else
                        echo "Warning: Report was not generated"
                      fi
                    failureStrategies:
                      - onFailure:
                          errors:
                            - AllErrors
                          action:
                            type: MarkAsSuccess
              - step:
                  type: RunTests
                  name: Unit Tests
                  identifier: unit_tests
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.SKIP_BUILD_TEST> == "false"
                  spec:
                    language: Java
                    buildTool: Maven
                    args: test
                    image: maven:3.9.6-eclipse-temurin-8
                    connectorRef: dockerhub_petclinic
                    additionalArgs: "-B -Dmaven.repo.local=/harness/.m2/repository -DargLine='-Xmx1024m -XX:MaxMetaspaceSize=512m' -DforkCount=1"
                    runOnlySelectedTests: false
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/surefire-reports/*.xml
    - stage:
        name: Build Images
        identifier: Build_All_Images
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            paths: []
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8s_docker_desktop
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - stepGroup:
                  name: Build All Images
                  identifier: Build_All_Images
                  steps:
                    - parallel:
                        - step:
                            type: BuildAndPushDockerRegistry
                            name: API Gateway Image
                            identifier: build_push_gateway
                            spec:
                              connectorRef: dockerhub_push
                              repo: areger55/harness-se-lab-dockerhub-repo
                              tags:
                                - gateway-<+codebase.commitSha>
                                - gateway-latest
                              buildArgs:
                                MODULE: spring-petclinic-api-gateway
                        - step:
                            type: BuildAndPushDockerRegistry
                            name: Customers Image
                            identifier: build_push_customers
                            spec:
                              connectorRef: dockerhub_push
                              repo: areger55/harness-se-lab-dockerhub-repo
                              tags:
                                - customers-<+codebase.commitSha>
                                - customers-latest
                              buildArgs:
                                MODULE: spring-petclinic-customers-service
                        - step:
                            type: BuildAndPushDockerRegistry
                            name: Vets Image
                            identifier: build_push_vets
                            spec:
                              connectorRef: dockerhub_push
                              repo: areger55/harness-se-lab-dockerhub-repo
                              tags:
                                - vets-<+codebase.commitSha>
                                - vets-latest
                              buildArgs:
                                MODULE: spring-petclinic-vets-service
                        - step:
                            type: BuildAndPushDockerRegistry
                            name: Visits Image
                            identifier: build_push_visits
                            spec:
                              connectorRef: dockerhub_push
                              repo: areger55/harness-se-lab-dockerhub-repo
                              tags:
                                - visits-<+codebase.commitSha>
                                - visits-latest
                              buildArgs:
                                MODULE: spring-petclinic-visits-service
    - parallel:
        - stage:
            name: Deploy Customers to DEV
            identifier: deploy_customers_dev
            tags: {}
            template:
              templateRef: K8s_Canary_Deploy_v2
              versionLabel: v1
              templateInputs:
                type: Deployment
                variables:
                  - name: envRef
                    type: String
                    value: dev
                  - name: serviceName
                    type: String
                    value: customersservice
                  - name: appName
                    type: String
                    value: customers
                  - name: canaryCount
                    type: Number
                    value: <+pipeline.variables.CANARY_POD_COUNT>
        - stage:
            name: Deploy Vets to DEV
            identifier: deploy_vets_dev
            tags: {}
            template:
              templateRef: K8s_Canary_Deploy_v2
              versionLabel: v1
              templateInputs:
                type: Deployment
                variables:
                  - name: envRef
                    type: String
                    value: dev
                  - name: serviceName
                    type: String
                    value: vetsservice
                  - name: appName
                    type: String
                    value: vets
                  - name: canaryCount
                    type: Number
                    value: <+pipeline.variables.CANARY_POD_COUNT>
        - stage:
            name: Deploy Visits to DEV
            identifier: deploy_visits_dev
            tags: {}
            template:
              templateRef: K8s_Canary_Deploy_v2
              versionLabel: v1
              templateInputs:
                type: Deployment
                variables:
                  - name: envRef
                    type: String
                    value: dev
                  - name: serviceName
                    type: String
                    value: visitsservice
                  - name: appName
                    type: String
                    value: visits
                  - name: canaryCount
                    type: Number
                    value: <+pipeline.variables.CANARY_POD_COUNT>
        - stage:
            name: Deploy Gateway to DEV
            identifier: deploy_gateway_dev
            tags: {}
            template:
              templateRef: K8s_Canary_Deploy_v2
              versionLabel: v1
              templateInputs:
                type: Deployment
                variables:
                  - name: envRef
                    type: String
                    value: dev
                  - name: serviceName
                    type: String
                    value: apigatewayservice
                  - name: appName
                    type: String
                    value: visits
                  - name: canaryCount
                    type: Number
                    value: <+pipeline.variables.CANARY_POD_COUNT>
