pipeline:
  name: petclinic-ci-cd
  identifier: petclinic_ci_cd
  projectIdentifier: SE_Candidate_Lab
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_petclinic
        repoName: adamreger/spring-petclinic-k8s
        build: <+input>
  variables:
    - name: SKIP_DEPCHECK
      type: String
      value: <+input>.default(false).selectOneFrom(true,false)
    - name: SKIP_BUILD_TEST
      type: String
      value: <+input>.default(false).selectOneFrom(true,false)
    - name: CANARY_POD_COUNT
      type: String
      value: "1"
  stages:
    - stage:
        name: Build and Test
        identifier: Build_Test
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8s_docker_desktop
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build
                  identifier: mvn_build
                  spec:
                    shell: Sh
                    image: maven:3.9.6-eclipse-temurin-8
                    connectorRef: dockerhub_petclinic
                    envVariables:
                      NVD_API_KEY: <+secrets.getValue("NVD_API_KEY")>
                    resources:
                      limits:
                        memory: 3Gi
                        cpu: "2"
                      requests:
                        memory: 1Gi
                        cpu: "1"
                    command: |
                      unset MAVEN_CONFIG
                      chmod +x mvnw
                      java -version && ./mvnw -v
                      export MAVEN_OPTS="-Xms512m -Xmx1536m -XX:MaxMetaspaceSize=512m"
                      mkdir -p /harness/.m2/repository
                      ./mvnw -B -Dmaven.repo.local=/harness/.m2/repository -DskipTests clean package
              - step:
                  type: Run
                  name: Check Dependencies
                  identifier: Check_Dependencies
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.SKIP_DEPCHECK> == "false"
                  spec:
                    connectorRef: dockerhub_petclinic
                    image: maven:3.9.6-eclipse-temurin-17
                    shell: Sh
                    envVariables:
                      NVD_API_KEY: <+secrets.getValue("NVD_API_KEY")>
                    command: |-
                      unset MAVEN_CONFIG
                      export MAVEN_OPTS="-Xms256m -Xmx1024m -XX:MaxMetaspaceSize=384m"
                      mkdir -p /harness/.m2/repository
                      rm -rf /harness/.m2/repository/org/owasp/dependency-check-data
                      DC_DATA_DIR=$(mktemp -d /tmp/dc-data-XXXXXX)
                      trap "rm -rf ${DC_DATA_DIR}" EXIT
                      DEP_CHECK_VERSION=11.2.0
                      echo "Running OWASP Dependency-Check ${DEP_CHECK_VERSION} with Java $(java -version 2>&1 | head -n 1)"
                      ./mvnw -B \
                      -Dmaven.repo.local=/harness/.m2/repository \
                      -DnvdApiKey=${NVD_API_KEY} \
                      -DskipTests \
                      -Dorg.owasp.dependencycheck.data.directory=${DC_DATA_DIR} \
                      -DdataDirectory=${DC_DATA_DIR} \
                      -Dnvd.api.threadCount=1 \
                      -Danalyze.from=1925 \
                      -DdependencyCheck.failOnError=false \
                      org.owasp:dependency-check-maven:${DEP_CHECK_VERSION}:check
              - step:
                  type: RunTests
                  name: Unit Tests
                  identifier: unit_tests
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.SKIP_BUILD_TEST> == "false"
                  spec:
                    language: Java
                    buildTool: Maven
                    args: test
                    image: maven:3.9.6-eclipse-temurin-8
                    connectorRef: dockerhub_petclinic
                    additionalArgs: "-B -DnvdApiKey=${NVD_API_KEY} -Dmaven.repo.local=/harness/.m2/repository -DargLine='-Xmx1024m -XX:MaxMetaspaceSize=512m' -DforkCount=1"
                    runOnlySelectedTests: false
                    resources:
                      limits:
                        memory: 3Gi
                        cpu: "2"
                      requests:
                        memory: 1Gi
                        cpu: "1"
                    envVariables:
                      NVD_API_KEY: <+secrets.getValue("NVD_API_KEY")>
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/surefire-reports/*.xml
          caching:
            enabled: true
            paths: []
          buildIntelligence:
            enabled: true
        description: ""
    - stage:
        name: Build Image and Push
        identifier: Buildpack_Image
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8s_docker_desktop
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Customers Image
                  identifier: build_push_customers
                  spec:
                    connectorRef: dockerhub_push
                    repo: areger55/harness-se-lab-dockerhub-repo
                    tags:
                      - customers-<+codebase.commitSha>
                      - customers-latest
                    context: spring-petclinic-customers-service
                    dockerfile: spring-petclinic-customers-service/Dockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Vets Image
                  identifier: build_push_vets
                  spec:
                    connectorRef: dockerhub_push
                    repo: areger55/harness-se-lab-dockerhub-repo
                    tags:
                      - vets-<+codebase.commitSha>
                      - vets-latest
                    context: spring-petclinic-vets-service
                    dockerfile: spring-petclinic-vets-service/Dockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Visits Image
                  identifier: build_push_visits
                  spec:
                    connectorRef: dockerhub_push
                    repo: areger55/harness-se-lab-dockerhub-repo
                    tags:
                      - visits-<+codebase.commitSha>
                      - visits-latest
                    context: spring-petclinic-visits-service
                    dockerfile: spring-petclinic-visits-service/Dockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: API Gateway Image
                  identifier: build_push_gateway
                  spec:
                    connectorRef: dockerhub_push
                    repo: areger55/harness-se-lab-dockerhub-repo
                    tags:
                      - gateway-<+codebase.commitSha>
                      - gateway-latest
                    context: spring-petclinic-api-gateway
                    dockerfile: spring-petclinic-api-gateway/Dockerfile
          caching:
            enabled: true
            paths: []
          buildIntelligence:
            enabled: true
        description: ""
    - stage:
        name: Deploy API-Gateway
        identifier: Deploy_to_Dev
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: apigatewayservice
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: PipelineRollback
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: harnessk8sinfradev
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: PipelineRollback
          execution:
            steps:
              - stepGroup:
                  name: Canary Deployment
                  identifier: canaryDeployment
                  steps:
                    - step:
                        name: Canary Deployment
                        identifier: canaryDeployment
                        type: K8sCanaryDeploy
                        timeout: 10m
                        spec:
                          instanceSelection:
                            type: Count
                            spec:
                              count: <+pipeline.variables.CANARY_POD_COUNT>
                          skipDryRun: false
                    - step:
                        name: Observe Canary
                        identifier: observeCanary
                        type: Wait
                        timeout: 10m
                        spec:
                          duration: 1m
                    - step:
                        name: Check Canary Health
                        identifier: checkCanaryHealth
                        type: ShellScript
                        timeout: 10m
                        spec:
                          shell: Bash
                          onDelegate: true
                          source:
                            type: Inline
                            spec:
                              script: |
                                set -euo pipefail
                                echo "Checking canary rollout status..."
                                status=0
                                if ! kubectl rollout status deployment/api-gateway-canary --namespace petclinic --timeout=180s; then
                                  status=$?
                                  echo "Canary deployment did not become ready within timeout (exit code ${status})."
                                fi
                                echo "Listing canary pods for quick inspection:"
                                kubectl get pods --namespace petclinic -l harness.io/canary=true -o wide
                                echo "Fetching recent logs from canary pod(s) for diagnostics..."
                                mapfile -t pods < <(kubectl get pods --namespace petclinic -l harness.io/canary=true -o name)
                                if [ ${#pods[@]} -eq 0 ]; then
                                  echo "No canary pods found to fetch logs from."
                                else
                                  for pod in "${pods[@]}"; do
                                    echo "----- Logs for ${pod} -----"
                                    kubectl logs --namespace petclinic "${pod}" --tail=200 || true
                                    echo "----- End logs for ${pod} -----"
                                  done
                                fi
                                exit ${status}
                          environmentVariables: []
                          outputVariables: []
                    - step:
                        name: Canary Delete
                        identifier: canaryDelete
                        type: K8sCanaryDelete
                        timeout: 10m
                        spec: {}
              - stepGroup:
                  name: Primary Deployment
                  identifier: primaryDeployment
                  steps:
                    - step:
                        name: Rolling Deployment
                        identifier: rollingDeployment
                        type: K8sRollingDeploy
                        timeout: 10m
                        spec:
                          skipDryRun: false
            rollbackSteps:
              - step:
                  name: Canary Delete
                  identifier: rollbackCanaryDelete
                  type: K8sCanaryDelete
                  timeout: 10m
                  spec: {}
              - step:
                  name: Rolling Rollback
                  identifier: rollingRollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
