pipeline:
  name: petclinic-ci-cd
  identifier: petclinic_ci_cd
  projectIdentifier: SE_Candidate_Lab
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_petclinic
        repoName: adamreger/spring-petclinic-k8s
        build: <+input>
  variables:
    - name: SKIP_DEPCHECK
      type: String
      value: <+input>.default(true).selectOneFrom(true,false)
    - name: SKIP_DEPCHECK_NEW
      type: String
      value: <+input>.default(true).selectOneFrom(true,false)
    - name: SKIP_BUILD_TEST
      type: String
      value: <+input>.default(false).selectOneFrom(true,false)
    - name: CANARY_POD_COUNT
      type: String
      value: <+input>.default(1)
  stages:
    - stage:
        name: Build and Test
        identifier: Build_Test
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8s_docker_desktop
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build
                  identifier: mvn_build
                  spec:
                    shell: Sh
                    image: maven:3.9.6-eclipse-temurin-8
                    connectorRef: dockerhub_petclinic
                    envVariables:
                      NVD_API_KEY: <+secrets.getValue("NVD_API_KEY")>
                    resources:
                      limits:
                        memory: 3Gi
                        cpu: "2"
                      requests:
                        memory: 1Gi
                        cpu: "1"
                    command: |
                      unset MAVEN_CONFIG
                      chmod +x mvnw
                      java -version && ./mvnw -v
                      export MAVEN_OPTS="-Xms512m -Xmx1536m -XX:MaxMetaspaceSize=512m"
                      mkdir -p /harness/.m2/repository
                      ./mvnw -B -Dmaven.repo.local=/harness/.m2/repository -DskipTests clean package
              - step:
                  type: Run
                  name: Check Dependencies
                  identifier: Check_Dependencies
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.SKIP_DEPCHECK> == "false"
                  spec:
                    connectorRef: dockerhub_petclinic
                    image: maven:3.9.6-eclipse-temurin-17
                    shell: Sh
                    envVariables:
                      NVD_API_KEY: <+secrets.getValue("NVD_API_KEY")>
                    command: |-
                      unset MAVEN_CONFIG
                      export MAVEN_OPTS="-Xms256m -Xmx1024m -XX:MaxMetaspaceSize=384m"
                      DC_VERSION=12.0.2
                      DC_ARCHIVE="dependency-check-cli-${DC_VERSION}-release.zip"
                      DC_BASE_PATH="${HOME}/.dependency-check"
                      DC_BIN="${DC_BASE_PATH}/${DC_VERSION}"
                      mkdir -p "${DC_BIN}"
                      if [ ! -d "${DC_BIN}/dependency-check" ]; then
                        DC_URL="https://repo1.maven.org/maven2/org/owasp/dependency-check-cli/${DC_VERSION}/${DC_ARCHIVE}"
                        echo "Downloading OWASP Dependency-Check CLI ${DC_VERSION} from ${DC_URL}"
                        APT_UPDATED=false
                        if ! command -v curl >/dev/null 2>&1; then
                          apt-get update && apt-get install -y curl
                          APT_UPDATED=true
                        fi
                        if ! command -v unzip >/dev/null 2>&1; then
                          if [ "${APT_UPDATED}" = "false" ]; then
                            apt-get update
                          fi
                          apt-get install -y unzip
                        fi
                        rm -rf "${DC_BIN:?}/${DC_ARCHIVE}" "${DC_BIN:?}/dependency-check"
                        curl -fsSL "${DC_URL}" -o "${DC_BIN}/${DC_ARCHIVE}"
                        unzip -q "${DC_BIN}/${DC_ARCHIVE}" -d "${DC_BIN}"
                      else
                        echo "Reusing cached Dependency-Check CLI ${DC_VERSION}"
                      fi
                      DC_HOME="${DC_BIN}/dependency-check"
                      DC_DATA_DIR="${DC_BASE_PATH}/data"
                      rm -rf "${DC_DATA_DIR}"
                      mkdir -p "${DC_DATA_DIR}"
                      echo "Updating vulnerability database"
                      "${DC_HOME}/bin/dependency-check.sh" \
                        --data "${DC_DATA_DIR}" \
                        --updateonly \
                        --nvdApiKey "${NVD_API_KEY}" \
                        --nvdApiDelay 4000
                      echo "Running OWASP Dependency-Check CLI ${DC_VERSION}"
                      mkdir -p dependency-check-report
                      "${DC_HOME}/bin/dependency-check.sh" \
                        --project "spring-petclinic" \
                        --scan "spring-petclinic-api-gateway" \
                        --out "dependency-check-report" \
                        --data "${DC_DATA_DIR}" \
                        --format "HTML" \
                        --format "JSON" \
                        --noupdate \
                        --failOnCVSS 11
                      echo "Dependency-Check reports generated under dependency-check-report/"
              - step:
                  type: Run
                  name: OWASP Dependency Check
                  identifier: owasp_dependency_check
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.SKIP_DEPCHECK_NEW> == "false"
                  spec:
                    connectorRef: dockerhub_petclinic
                    image: maven:3.9.6-eclipse-temurin-17
                    shell: Sh
                    envVariables:
                      NVD_API_KEY: <+secrets.getValue("NVD_API_KEY")>
                    resources:
                      limits:
                        memory: 3Gi
                        cpu: "2"
                      requests:
                        memory: 1Gi
                        cpu: "1"
                    command: |
                      # Clean up any previously cached plugin artifacts to avoid version conflicts
                      rm -rf /harness/.m2/repository/org/owasp/dependency-check-maven/

                      # Run OWASP Dependency Check with Java 17 compatible settings
                      mvn -B -Dmaven.repo.local=/harness/.m2/repository \
                        org.owasp:dependency-check-maven:check \
                        -DfailBuildOnCVSS=7 \
                        -Dformat=ALL \
                        -DprettyPrint=true \
                        -DnvdApiKey=${NVD_API_KEY} \
                        -DskipSystemScope=false

                      # Check if vulnerabilities were found
                      if [ -f target/dependency-check-report.html ]; then
                        echo "Dependency check report generated successfully"
                        echo "Report location: target/dependency-check-report.html"
                      else
                        echo "Warning: Report was not generated"
                      fi
                    failureStrategies:
                      - onFailure:
                          errors:
                            - AllErrors
                          action:
                            type: MarkAsSuccess
              - step:
                  type: RunTests
                  name: Unit Tests
                  identifier: unit_tests
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.SKIP_BUILD_TEST> == "false"
                  spec:
                    language: Java
                    buildTool: Maven
                    args: test
                    image: maven:3.9.6-eclipse-temurin-8
                    connectorRef: dockerhub_petclinic
                    additionalArgs: "-B -Dmaven.repo.local=/harness/.m2/repository -DargLine='-Xmx1024m -XX:MaxMetaspaceSize=512m' -DforkCount=1"
                    runOnlySelectedTests: false
                    resources:
                      limits:
                        memory: 3Gi
                        cpu: "2"
                      requests:
                        memory: 1Gi
                        cpu: "1"
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/surefire-reports/*.xml
          caching:
            enabled: true
            paths: []
          buildIntelligence:
            enabled: true
        description: ""
    - stage:
        name: Build Image and Push
        identifier: Buildpack_Image
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8s_docker_desktop
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Customers Image
                  identifier: build_push_customers
                  spec:
                    connectorRef: dockerhub_push
                    repo: areger55/harness-se-lab-dockerhub-repo
                    tags:
                      - customers-<+codebase.commitSha>
                      - customers-latest
                    context: spring-petclinic-customers-service
                    dockerfile: spring-petclinic-customers-service/Dockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Vets Image
                  identifier: build_push_vets
                  spec:
                    connectorRef: dockerhub_push
                    repo: areger55/harness-se-lab-dockerhub-repo
                    tags:
                      - vets-<+codebase.commitSha>
                      - vets-latest
                    context: spring-petclinic-vets-service
                    dockerfile: spring-petclinic-vets-service/Dockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Visits Image
                  identifier: build_push_visits
                  spec:
                    connectorRef: dockerhub_push
                    repo: areger55/harness-se-lab-dockerhub-repo
                    tags:
                      - visits-<+codebase.commitSha>
                      - visits-latest
                    context: spring-petclinic-visits-service
                    dockerfile: spring-petclinic-visits-service/Dockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: API Gateway Image
                  identifier: build_push_gateway
                  spec:
                    connectorRef: dockerhub_push
                    repo: areger55/harness-se-lab-dockerhub-repo
                    tags:
                      - gateway-<+codebase.commitSha>
                      - gateway-latest
                    context: spring-petclinic-api-gateway
                    dockerfile: spring-petclinic-api-gateway/Dockerfile
          caching:
            enabled: true
            paths: []
          buildIntelligence:
            enabled: true
        description: ""
    - stage:
        name: Deploy API-Gateway
        identifier: Deploy_to_Dev
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: apigatewayservice
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: PipelineRollback
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: harnessk8sinfradev
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: PipelineRollback
          execution:
            steps:
              - stepGroup:
                  name: Canary Deployment
                  identifier: canaryDeployment
                  steps:
                    - step:
                        name: Canary Deployment
                        identifier: canaryDeployment
                        type: K8sCanaryDeploy
                        timeout: 10m
                        spec:
                          instanceSelection:
                            type: Count
                            spec:
                              count: <+pipeline.variables.CANARY_POD_COUNT>
                          skipDryRun: false
                    - step:
                        name: Observe Canary
                        identifier: observeCanary
                        type: Wait
                        timeout: 10m
                        spec:
                          duration: 1m
                    - step:
                        name: Check Canary Health
                        identifier: checkCanaryHealth
                        type: ShellScript
                        timeout: 10m
                        spec:
                          shell: Bash
                          onDelegate: true
                          source:
                            type: Inline
                            spec:
                              script: |
                                set -euo pipefail
                                echo "Checking canary rollout status..."
                                status=0
                                if ! kubectl rollout status deployment/api-gateway-canary --namespace petclinic --timeout=180s; then
                                  status=$?
                                  echo "Canary deployment did not become ready within timeout (exit code ${status})."
                                fi
                                echo "Listing canary pods for quick inspection:"
                                kubectl get pods --namespace petclinic -l harness.io/canary=true -o wide
                                echo "Fetching recent logs from canary pod(s) for diagnostics..."
                                mapfile -t pods < <(kubectl get pods --namespace petclinic -l harness.io/canary=true -o name)
                                if [ ${#pods[@]} -eq 0 ]; then
                                  echo "No canary pods found to fetch logs from."
                                else
                                  for pod in "${pods[@]}"; do
                                    echo "----- Logs for ${pod} -----"
                                    kubectl logs --namespace petclinic "${pod}" --tail=200 || true
                                    echo "----- End logs for ${pod} -----"
                                  done
                                fi
                                exit ${status}
                          environmentVariables: []
                          outputVariables: []
                    - step:
                        name: Canary Delete
                        identifier: canaryDelete
                        type: K8sCanaryDelete
                        timeout: 10m
                        spec: {}
              - stepGroup:
                  name: Primary Deployment
                  identifier: primaryDeployment
                  steps:
                    - step:
                        name: Rolling Deployment
                        identifier: rollingDeployment
                        type: K8sRollingDeploy
                        timeout: 10m
                        spec:
                          skipDryRun: false
            rollbackSteps:
              - step:
                  name: Canary Delete
                  identifier: rollbackCanaryDelete
                  type: K8sCanaryDelete
                  timeout: 10m
                  spec: {}
              - step:
                  name: Rolling Rollback
                  identifier: rollingRollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
