pipeline:
  projectIdentifier: SE_Candidate_Lab
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_petclinic
        build: <+input>
  variables:
    - name: SKIP_DEPCHECK
      type: String
      value: "true"
    - name: SKIP_BUILD_TEST
      type: String
      value: "true"
    - name: CANARY_POD_COUNT
      type: String
      value: "1"
  stages:
    - stage:
        name: Deploy API-Gateway
        identifier: Deploy_to_Dev
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: apigatewayservice
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: PipelineRollback
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: harnessk8sinfradev
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: PipelineRollback
          execution:
            steps:
              - stepGroup:
                  name: Canary Deployment
                  identifier: canaryDeployment
                  steps:
                    - step:
                        name: Canary Deployment
                        identifier: canaryDeployment
                        type: K8sCanaryDeploy
                        timeout: 10m
                        spec:
                          instanceSelection:
                            type: Count
                            spec:
                              count: <+pipeline.variables.CANARY_POD_COUNT>
                          skipDryRun: false
                    - step:
                        name: Observe Canary
                        identifier: observeCanary
                        type: Wait
                        timeout: 10m
                        spec:
                          duration: 2m
                    - step:
                        name: Check Canary Health
                        identifier: checkCanaryHealth
                        type: ShellScript
                        timeout: 10m
                        spec:
                          shell: Bash
                          onDelegate: true
                          source:
                            type: Inline
                            spec:
                              script: |
                                set -eo pipefail
                                echo "Checking canary rollout status..."
                                kubectl rollout status deployment/api-gateway-canary --namespace petclinic --timeout=180s
                                echo "Listing canary pods for quick inspection:"
                                kubectl get pods --namespace petclinic -l harness.io/canary=true -o wide
                          environmentVariables: []
                          outputVariables: []
                    - step:
                        name: Canary Delete
                        identifier: canaryDelete
                        type: K8sCanaryDelete
                        timeout: 10m
                        spec: {}
              - stepGroup:
                  name: Primary Deployment
                  identifier: primaryDeployment
                  steps:
                    - step:
                        name: Rolling Deployment
                        identifier: rollingDeployment
                        type: K8sRollingDeploy
                        timeout: 10m
                        spec:
                          skipDryRun: false
            rollbackSteps:
              - step:
                  name: Canary Delete
                  identifier: rollbackCanaryDelete
                  type: K8sCanaryDelete
                  timeout: 10m
                  spec: {}
              - step:
                  name: Rolling Rollback
                  identifier: rollingRollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  identifier: petcliniccd
  name: petclinic-cd
