pipeline:
  name: petclinic-ci
  identifier: petcliniccinew
  projectIdentifier: SE_Candidate_Lab
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_petclinic
        build: <+input>
  variables:
    - name: SKIP_DEPCHECK
      type: String
      value: "true"
    - name: SKIP_BUILD_TEST
      type: String
      value: "true"
  stages:
    - stage:
        name: Build and Test
        identifier: build_and_test
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: true
            paths: []
          buildIntelligence:
            enabled: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8s_docker_desktop
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build
                  identifier: Build
                  spec:
                    shell: Sh
                    image: maven:3.9.6-eclipse-temurin-8
                    connectorRef: dockerhub_petclinic
                    envVariables:
                      NVD_API_KEY: <+secrets.getValue("NVD_API_KEY")>
                    resources:
                      limits:
                        memory: 3Gi
                        cpu: "2"
                      requests:
                        memory: 1Gi
                        cpu: "1"
                    command: |
                      unset MAVEN_CONFIG
                      chmod +x mvnw
                      java -version && ./mvnw -v
                      export MAVEN_OPTS="-Xms512m -Xmx1536m -XX:MaxMetaspaceSize=512m"
                      ./mvnw -B -Dmaven.repo.local=/harness/maven-repo -DskipTests clean package
              - step:
                  type: Run
                  name: Check Dependencies
                  identifier: Check_Dependencies
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.SKIP_DEPCHECK> == "false"
                  spec:
                    connectorRef: dockerhub_petclinic
                    image: maven:3.9.6-eclipse-temurin-8
                    shell: Sh
                    envVariables:
                      NVD_API_KEY: <+secrets.getValue("NVD_API_KEY")>
                    command: |-
                      unset MAVEN_CONFIG
                      export MAVEN_OPTS="-Xms256m -Xmx1024m -XX:MaxMetaspaceSize=384m"
                      ./mvnw -B \
                      -Dmaven.repo.local=/harness/maven-repo \
                      -DnvdApiKey=${NVD_API_KEY} \
                      -DskipTests \
                      org.owasp:dependency-check-maven:check
              - step:
                  type: RunTests
                  name: Unit Tests
                  identifier: unit_tests
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.SKIP_BUILD_TEST> == "false"
                  spec:
                    language: Java
                    buildTool: Maven
                    args: test
                    image: maven:3.9.6-eclipse-temurin-8
                    connectorRef: dockerhub_petclinic
                    additionalArgs: "-B -DnvdApiKey=${NVD_API_KEY} -Dmaven.repo.local=/harness/maven-repo -DargLine='-Xmx1024m -XX:MaxMetaspaceSize=512m' -DforkCount=1"
                    runOnlySelectedTests: false
                    resources:
                      limits:
                        memory: 3Gi
                        cpu: "2"
                      requests:
                        memory: 1Gi
                        cpu: "1"
                    envVariables:
                      NVD_API_KEY: <+secrets.getValue("NVD_API_KEY")>
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/surefire-reports/*.xml
    - stage:
        name: Build Image and Push
        identifier: Build_Images
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8s_docker_desktop
              namespace: harness-delegate-ng
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Customers Image
                  identifier: build_push_customers
                  spec:
                    connectorRef: dockerhub_push
                    repo: areger55/harness-se-lab-dockerhub-repo
                    tags:
                      - customers-<+codebase.commitSha>
                      - customers-latest
                    context: spring-petclinic-customers-service
                    dockerfile: spring-petclinic-customers-service/Dockerfile
                    baseImageConnectorRefs:
                      - dockerhub_push
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Vets Image
                  identifier: build_push_vets
                  spec:
                    connectorRef: dockerhub_push
                    repo: areger55/harness-se-lab-dockerhub-repo
                    tags:
                      - vets-<+codebase.commitSha>
                      - vets-latest
                    context: spring-petclinic-vets-service
                    dockerfile: spring-petclinic-vets-service/Dockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Visits Image
                  identifier: build_push_visits
                  spec:
                    connectorRef: dockerhub_push
                    repo: areger55/harness-se-lab-dockerhub-repo
                    tags:
                      - visits-<+codebase.commitSha>
                      - visits-latest
                    context: spring-petclinic-visits-service
                    dockerfile: spring-petclinic-visits-service/Dockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: API Gateway Image
                  identifier: build_push_gateway
                  spec:
                    connectorRef: dockerhub_push
                    repo: areger55/harness-se-lab-dockerhub-repo
                    tags:
                      - gateway-<+codebase.commitSha>
                      - gateway-latest
                    context: spring-petclinic-api-gateway
                    dockerfile: spring-petclinic-api-gateway/Dockerfile
